-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (SELECT SALES_DATE, 
       PRODUCT_ID, 
       USER_ID, 
       SALES_AMOUNT
      FROM ONLINE_SALE 
      
      UNION ALL
      
      (SELECT SALES_DATE, 
       PRODUCT_ID, 
       CAST(NULL AS NUMBER) USER_ID, 
       SALES_AMOUNT 
       FROM OFFLINE_SALE))
       
WHERE SALES_DATE between DATE '2022-03-01' and DATE '2022-03-31'
ORDER BY SALES_DATE , PRODUCT_ID , USER_ID;