-- 코드를 입력하세요
SELECT 
    c.CAR_ID, 
    c.CAR_TYPE, 
    ROUND(c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
  ON c.CAR_TYPE = p.CAR_TYPE
 AND p.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND c.CAR_ID NOT IN (
      SELECT h.CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
      WHERE h.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
        AND h.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
  )
  AND (c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100) * 30) BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC, 
    CAR_TYPE ASC, 
    CAR_ID DESC;
